name: Publish library
on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Publish package
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish documentation
        run: |
          git config user.email "ci@josephearl.co.uk"
          git config user.name "ci"
          git fetch origin gh-pages
          git checkout gh-pages
          cp -r build/docs/javadoc/* .
          git add .
          git commit -m "Update documentation" && git push || true
